serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 1101
  path: /api/idm

loggerConfig:
  outputDir: ./logs/
  outputFile: IDMService.log

databaseConfig:
  dbUsername:
  dbPassword:
  dbHostname: localhost
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName:
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

sessionConfig:
  timeout: 1000000
  expiration: 1000000