serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 1234
  path: /api/idm

loggerConfig:
  outputDir: ./logs/
  outputFile: IDMService.log

databaseConfig:
  dbUsername: root
  dbPassword: root
  dbHostname: localhost
  dbPort: 1101
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: SuperDelivery
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

sessionConfig:
  timeout: 1000000
  expiration: 1000000